---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: mode_example_test
    run_list:
      - recipe[mode_example_test::file]
