---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: mode_example_test
    run_list:
      - recipe[mode_example_test::file]
